env:
  browser: true
  es2021: true
extends: [
  eslint:recommended,
  plugin:@typescript-eslint/recommended
]
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins: [
  '@typescript-eslint'
]
ignorePatterns: [
  'examples/**/*',
  'dist/**/*',
  'tests/**/*',
  'docs/**/*',
  node_modules/**/*
]
rules:
  indent: [
    error,
    4,
    { SwitchCase: 1 }
  ]
  linebreak-style: [
    error,
    unix
  ]
  quotes: [
    error,
    single
  ]
  semi: [
    error,
    always
  ]
